services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
    networks:
      - proxy

networks:
  proxy:
    external: true
